### ISSUE TITLE
好东西，希望能有粉丝交流群

### ISSUE THREAD

**Issue by houpi** [roacn/pve#1]
如题，搞个tg交流群？另外请教设置语言包的必要性？我没有做这一步好像并没有影响。

**Comment by houpi** [comment]
另外请求添加openclash。依赖比较多，内核版本又太高，自己安装还是有点麻烦！

**Comment by roacn** [comment]
仅仅为了兼容而已，不设置语言包可以的，一般没问题。

[聊天吹水群](https://t.me/heiheiheio)
