### ISSUE TITLE
关于PVE更换源的看法

### ISSUE THREAD

**Issue by OldLi1997** [roacn/pve#6]
Pve_no_subscription_list="/etc/apt/sources.list.d/pve-no-subscription.list"
Pve_enterprise_list="/etc/apt/sources.list.d/pve-enterprise.list"

PVE需要的是pve-enterprise.list，而不是pve-no-subscription.list（如果一定要显示有效的存储库的话可以忽视此条建议）

**Comment by roacn** [comment]
.list格式文件名称可以随意，对使用不影响

**Comment by OldLi1997** [comment]
> .list格式文件名称可以随意，对使用不影响

那没问题了我这测试了，就是其他的注释不需要留吧感觉
